== rpi-splash-screen-support

This package provides a tool to configure and setup the fullscreen splash screen for Raspberry Pi OS.

This splash image is drawn early in the boot process. This tool will configure the kernel to show a fullscreen splash image at boot time, instead of the defualt four raspberries.

Upon operation, the only thing that should be drawn to the display will be the splash image, followed by whatever application overwrites it next (e.g. desktop, login console, etc).

== Requirements

* A 24-bit TGA image
* Image dimensions smaller than 1920x1080px
* Image must contain less than 224 colors


An example command to generate an image from a PNG file, to meet the requirements is given below.

```bash
convert logo.png -colors 224 -depth 8 -type TrueColor -alpha off -compress none -define tga:bits-per-sample=8 logo.tga
```

== Installation

To install the package, run the following command:

```bash
wget https://github.com/bebon901/configure-splash/raw/refs/heads/master/rpi-splash-screen-support_1.0.0_arm64.deb
sudo dpkg -i rpi-splash-screen-support_1.0.0_arm64.deb
```

== Usage

To configure the splash screen, run the following command, replacing <splash-image> with the path of the image file to use. This path can be relative or absolute.

```bash
sudo configure-splash <splash-image>
```

This will provide the necessary changes to the kernel to enable the splash screen.
